### ISSUE TITLE
Doesn't work as described.

### ISSUE THREAD

**Issue by enricribas** [jeremyevans/roda-sequel-stack#1]
If you copy and paste the instructions, you get an error when running

```
rake dev_up
```

Sequel::DatabaseConnectionError: PG::ConnectionBad: FATAL:  role "My_App" does not exist

If you add the user you get 

```
database doesn't exist My_App_development
```

if you add the database, you get...

```
Sequel::DatabaseError: PG::DuplicateTable: ERROR:  relation "model1s" already exists
```

If you change the name of the table in the migration to say "users" then it works

Then you run 

```
rake dev_irb
```

you get ....
```
Command failed with status (127):
```

**Comment by jeremyevans** [comment]
First, thanks for taking the time to try this out.

I think the README could use some additional explanation.  You aren't really supposed to run `rake dev_up` without first modifying the migration file, since it is unlikely you'll want a table in your database named `model1s`.  I'll fix the README soon.

There is a bug in the created `.env.rb` file, where the database name and database user name are not lower cased, I'll fix that as well.

**Comment by jeremyevans** [comment]
I've pushed a commit that fixes the `.env.rb` issue and adds more explanation to the README.  Please let me know whether you think the current instructions are sufficient, if you have any ideas for improving them, or if you run into any other issues.

**Comment by jeremyevans** [comment]
I'm assuming this issue is fixed with the changes pushed last week.  If you still think there are problems, please open a new issue.  Thanks!

**Comment by ruthearle** [comment]
Hi Jeremy, there is still an issue with getting rake dev_up and rake dev_irb to run. 

```script
~/Dev/r_sewsocial (master ✘)ᐅ rake dev_irb
/Users/.rvm/rubies/irb-2.2.1/bin/ruby -r ./models
rake aborted!
Command failed with status (127): [/Users/.rvm/rubies/irb-2.2.1/bin/rub...]
/Users//Copy/Dev/r_sewsocial/Rakefile:54:in `block in <top (required)>'
/Users/Copy/Dev/r_sewsocial/Rakefile:64:in `call'
/Users/Copy/Dev/r_sewsocial/Rakefile:64:in `block in <top (required)>'
/Users/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => dev_irb
(See full trace by running task with --trace)
```

rake dev_up returns the same error as the OP but the database gets created. Any ideas?
